<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="28" started-at="2018-11-19T18:01:34Z" finished-at="2018-11-19T18:01:34Z">
    <groups>
    </groups>
    <test name="Validate URL" duration-ms="28" started-at="2018-11-19T18:01:34Z" finished-at="2018-11-19T18:01:34Z">
      <class name="validation.NavigateURL">
        <test-method status="FAIL" signature="initialize()[pri:0, instance:validation.NavigateURL@1324409e]" name="initialize" is-config="true" duration-ms="0" started-at="2018-11-19T23:31:34Z" finished-at="2018-11-19T23:31:34Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at repository.BaseFile.initializeDriver(BaseFile.java:24)
	at validation.NavigateURL.initialize(NavigateURL.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="SKIP" signature="navigateURL()[pri:0, instance:validation.NavigateURL@1324409e]" name="navigateURL" duration-ms="0" started-at="2018-11-19T23:31:34Z" finished-at="2018-11-19T23:31:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateURL -->
        <test-method status="SKIP" signature="tearDown()[pri:0, instance:validation.NavigateURL@1324409e]" name="tearDown" is-config="true" duration-ms="0" started-at="2018-11-19T23:31:34Z" finished-at="2018-11-19T23:31:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- validation.NavigateURL -->
    </test> <!-- Validate URL -->
  </suite> <!-- Suite -->
</testng-results>
